"""empty message

Revision ID: 1571fcd2a333
Revises: e33784d18fbe
Create Date: 2022-11-27 22:30:07.456586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1571fcd2a333'
down_revision = 'e33784d18fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'notification', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'notification', 'user', ['user_id'], ['id'])
    op.drop_column('notification', 'towards')
    op.create_foreign_key(None, 'photo', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.add_column('notification', sa.Column('towards', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_constraint(None, 'notification', type_='foreignkey')
    # ### end Alembic commands ###
