"""empty message

Revision ID: 258c15c0ac60
Revises: a3650e63e588
Create Date: 2022-11-23 14:01:20.669213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258c15c0ac60'
down_revision = 'a3650e63e588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('num_likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'num_likes')
    # ### end Alembic commands ###
