"""empty message

Revision ID: 3d78a620907c
Revises: 8dea876eb737
Create Date: 2022-11-27 22:06:50.819019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d78a620907c'
down_revision = '8dea876eb737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'notifation', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'notifation', 'user', ['user_id'], ['id'])
    op.drop_column('notifation', 'towards')
    op.create_foreign_key(None, 'photo', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.add_column('notifation', sa.Column('towards', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'notifation', type_='foreignkey')
    op.drop_constraint(None, 'notifation', type_='foreignkey')
    # ### end Alembic commands ###
