"""empty message

Revision ID: 90e07de81390
Revises: 1571fcd2a333
Create Date: 2022-11-27 23:11:50.651557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e07de81390'
down_revision = '1571fcd2a333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifation', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notifation', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'notifation', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'notifation', 'comment', ['comment_id'], ['id'])
    op.drop_column('notifation', 'towards')
    op.create_foreign_key(None, 'photo', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.add_column('notifation', sa.Column('towards', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'notifation', type_='foreignkey')
    op.drop_constraint(None, 'notifation', type_='foreignkey')
    op.drop_constraint(None, 'notifation', type_='foreignkey')
    op.drop_column('notifation', 'comment_id')
    # ### end Alembic commands ###
