"""empty message

Revision ID: a3650e63e588
Revises: cdc1eb786bad
Create Date: 2022-11-23 00:09:52.512224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3650e63e588'
down_revision = 'cdc1eb786bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_like_comment',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('commment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_like_comment')
    # ### end Alembic commands ###
