"""empty message

Revision ID: bab425f18e03
Revises: 0f0ff55d4d27
Create Date: 2022-11-27 21:08:50.853220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab425f18e03'
down_revision = '0f0ff55d4d27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('towards', sa.Integer(), nullable=True))
    op.add_column('notifation', sa.Column('state', sa.Integer(), nullable=True))
    op.add_column('notifation', sa.Column('action', sa.Integer(), nullable=True))
    op.add_column('notifation', sa.Column('object', sa.Integer(), nullable=True))
    op.add_column('notifation', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('notifation', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notifation', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'notifation', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'photo', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.drop_constraint(None, 'notifation', type_='foreignkey')
    op.drop_constraint(None, 'notifation', type_='foreignkey')
    op.drop_column('notifation', 'post_id')
    op.drop_column('notifation', 'user_id')
    op.drop_column('notifation', 'object')
    op.drop_column('notifation', 'action')
    op.drop_column('notifation', 'state')
    op.drop_column('comment', 'towards')
    # ### end Alembic commands ###
