"""empty message

Revision ID: e33784d18fbe
Revises: 3d78a620907c
Create Date: 2022-11-27 22:19:18.091813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33784d18fbe'
down_revision = '3d78a620907c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifation', sa.Column('link', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'notifation', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'notifation', 'user', ['user_id'], ['id'])
    op.drop_column('notifation', 'towards')
    op.create_foreign_key(None, 'photo', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.add_column('notifation', sa.Column('towards', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'notifation', type_='foreignkey')
    op.drop_constraint(None, 'notifation', type_='foreignkey')
    op.drop_column('notifation', 'link')
    # ### end Alembic commands ###
